version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
  
  kafka-producer:
    build:
      context: ./kafka-producer
    depends_on:
      - kafka
    volumes:
      - ./configuration.yaml:/app/configuration.yaml

  kafka-consumer:
    build:
      context: ./kafka-consumer
    depends_on:
      - kafka
      - mongo
    volumes:
      - ./configuration.yaml:/app/configuration.yaml

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "37017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-etl:
    build:
      context: ./redis-etl
    depends_on:
      - mongo
      - redis
    volumes:
      - ./configuration.yaml:/app/configuration.yaml


volumes:
  mongo-data: